lv_conf.h, main/main.c
otherwise the esp32 will crash if cache is disabled (in my case during SPIFFS write).
Also add the attribute to your function:
static void IRAM_ATTR lv_tick_task(void)
=> IRAM_ATTR for the tick function

README.md
Add new configuration for ESP32 DevKit v4 with 38 GPIOS, based on "https://forum.littlevgl.com/t/issue-with-calibration-of-display-ili9341-display-and-xpt-2046-touch-controller/395/39"
=> Add new configuration section

components/drv/ili9341.c, components/drv/ili9341.h, main/main.c
fixes #18
The issue with my display being blank was the Touchpad SPI was being initialized even when it was disabled. Another ifdef in main solves this.
The next problem that I had is everything was inverted, like text written on a mirror. I had seen this before using the loboris driver, and created a similar configuration define.
Actually, this matter can become very complex, it seems from the [predefines](https://github.com/loboris/ESP32_TFT_library/blob/master/components/tft/tftspi.h#L72) and [switch logic](https://github.com/loboris/ESP32_TFT_library/blob/master/components/tft/tftspi.c#L788) there that there are a variety of orientation and rotation commands to achieve the same desired results just within different ili9341 based displays. An alternative to this madness might be to …
=> Don't Init Disabled Touchpad SPI / M5Stack Support

components/lvgl_ili9341/ili9341.c, components/lvgl_ili9341/ili9341.h
With `ili9341_enable_backlight(bool backlight)` the user will be able to turn on the backlight and turn it off, ex. when trying to save power.
=> [ili9341] Add helper function to turn on and off the display backlight.

components/lvgl_ili9341/Kconfig
So the user doesn't choose non existent gpio pin numbers. This doesn't validate if the selected pins are in fact able to do MOSI, SCK, etc, it just checks that the selected pin is not 40 or larger (esp32 only have up to 39 pins).
=> [Kconfig] Add basic ranges to valid GPIO numbers

components/lvgl_ili9341/Kconfig, components/lvgl_ili9341/ili9341.c
At the tail-end of #25, I had to make a change to support GCC 8.2 as it failed with a warning on while loops without a body.  I should have just made it empty braces on the busy waits, but at the time our discussion seemed to be leaning in the direction of adding a `taskYIELD()` in those loops. I mentioned that in [my last comment ](https://github.com/littlevgl/lv_port_esp32_ili9341/pull/25#issuecomment-548175391
) but maybe it was overlooked, and in our discussion of #30 I neglected to mention we already had some of these in the code base. Since we concluded there we don't need them, we should take them out now.
Also, I fix a minor KConfig issue: when you pick a pre-defined display (M5 or WRover Kit 4.1) you shouldn't see the backlight prompts since we already fill the correct values for …
=> Remove taskYIELD() Calls

components/lvgl_esp32_drivers/lvgl_tft/disp_spi.c
spi_device_queue_trans implicitly allocates capable memory (DMA and 32bit aligned) if provided buffer in spi_transaction_t structure is not.
But only spi_device_get_trans_result sets this free again. So without calling spi_device_get_trans_result there is a memory leak stalling application after just a few calls to spi_device_queue_trans.
=> correct handling of DMA buffers

components/lvgl_esp32_drivers/lvgl_touch/xpt2046.c
Fix warning
```c
xpt2046.c:55:29: warning: left shift count >= width of type [-Wshift-count-overflow]
.pin_bit_mask = 1UL << XPT2046_IRQ,
```
=> xpt2046: Fix warning left shift bigger than type

CMakeLists.txt, components/lv_examples/lv_ex_conf.h, components/lvgl_esp32_drivers/CMakeLists.txt, components/lvgl_esp32_drivers/component.mk, components/lvgl_esp32_drivers/lvgl_driver.c, components/lvgl_esp32_drivers/lvgl_driver.h, components/lvgl_esp32_drivers/lvgl_spi_conf.h, components/lvgl_esp32_drivers/lvgl_tft/disp_spi.c, components/lvgl_esp32_drivers/lvgl_tft/disp_spi.h, components/lvgl_esp32_drivers/lvgl_touch/touch_driver.c, components/lvgl_esp32_drivers/lvgl_touch/tp_spi.c, components/lvgl_esp32_drivers/lvgl_touch/tp_spi.h, main/CMakeLists.txt, main/main.c
Idea is to create a 'user friendly' driver meaning that `main.c` would look something like this:
```
...
#include "lvgl/lvgl.h"
#include "lvgl_driver.h"
...
void app_main() {
lv_init();
lvgl_driver_init();
...
}
```
I don't know if i configured `CMakeLists.txt` and `component.mk` correctly, but the demo program works (tested on ILI9341 and XPT2046 with shared SPI).
Probably the file/function names are not really the best, but this is only a suggestion...
=> created 'user friendly' driver

components/lvgl_esp32_drivers/lvgl_tft/Kconfig, components/lvgl_esp32_drivers/lvgl_tft/ili9341.c
Default values wasn't being taken into account so now that's fixed, also the backlight control pin option on the pin assignment menu is available only when backlight control is enabled.
Also generic cleanup, bool symbols default to n, so explicit **default n** were removed.
=> Update Kconfig for lvgl_tft

README.md, main/main.c
The example has been rewrote to use tasks.
I spent almost a night trying to understand a memory corruption, but this seems to work pretty well.
Tested successfully with high memory and CPU usage, high network traffic and concurrent i2s communication.
It pins the `guiTask` to only one core in order to prevent problem with SPI communication.
Uses `esp_timer_start_periodic` to call `lv_tick_task` periodically.
Uses Semaphores to show how to synchronize with different other tasks.
=> More complete example working with different peripherals

components/lvgl_esp32_drivers/lvgl_tft/Kconfig
For ER-TFTM035 and the default one to GPIO27.
Prev. GPIO21 is the I²C interface used by some touch controllers. 
GPIO27 has no important dedicated functionality
=> Change default backlight GPIO

components/lvgl_esp32_drivers/lvgl_tft/ili9488.c
In case of high DMA usage, the driver may not be able to allocate enough DMA capable memory resulting in a crash. Retry loop till enough memory becomes available.
Example of high DMA usage: High rate of HTTP requests & responses (>2048 bytes) via WiFi while updating big portions of the screen.
=> ILI9488: Fix low DMA crash - retry on allocation failure

components/lvgl_esp32_drivers/lvgl_tft/sh1107.c, components/lvgl_esp32_drivers/lvgl_tft/ssd1306.c, main/main.c
- Workaround using ssd1306_rounder() and sh1107_rounder() for ssd1306_flush() and sh1107_flush() which needs to be fixed.
- Fixed: lv_flush_ready() is called to early for sh1107
- Remove including lv_theme_mono.h
=> Fix monochrome displays using ssd1306 and sh1107

main/main.c
Fix the example because two screen-sized buffers cannot be used with set_px_cb callback set.
=> Fix example (with two screen-sized buffers and set_px_cb)

README.md
=> README: Add note about using make instead of idf.py when using ESP-IDF v3.x

components/lvgl_esp32_drivers/lvgl_tft/disp_spi.h
=> Declaring inline functions as static avoid them being optimized when using -Os

components/lvgl_esp32_drivers/lvgl_tft/ili9488.c
5-bit to 6-bit color conversion (RGB565 to RGB666) should fill LSB with copy of MSB.
=> ili9488: RGB666 conversion

components/lvgl_esp32_drivers/lvgl_tft/GC9A01.c, components/lvgl_esp32_drivers/lvgl_tft/hx8357.c, components/lvgl_esp32_drivers/lvgl_tft/il3820.c, components/lvgl_esp32_drivers/lvgl_tft/ili9341.c, components/lvgl_esp32_drivers/lvgl_tft/ili9481.c, components/lvgl_esp32_drivers/lvgl_tft/ili9486.c, components/lvgl_esp32_drivers/lvgl_tft/ili9488.c, components/lvgl_esp32_drivers/lvgl_tft/ra8875.c, components/lvgl_esp32_drivers/lvgl_tft/sh1107.c, components/lvgl_esp32_drivers/lvgl_tft/st7735s.c, components/lvgl_esp32_drivers/lvgl_tft/st7789.c
Some GPIOs (GPIO32 and GPIO33) need to be explicitly configured as gpios, as we don't know which pin are the users going to choose I think a good solution is to configure all the GPIOs.
Fixes part of #183, another PR will create the predefined display configuration for TTGO Camera Plus board.
=> Configure GPIOs pins as GPIO explicitly

components/lv_examples/CMakeLists.txt, components/lvgl/CMakeLists.txt, components/lvgl_esp32_drivers/CMakeLists.txt, components/lvgl_esp32_drivers/lvgl_tft/CMakeLists.txt, components/lvgl_esp32_drivers/lvgl_touch/CMakeLists.txt
Getting ready to add CMakeLists and Kconfig to lvgl and lv_examples main repo! Closes #190
=> Check for ESP_PLATFORM on CMakeLists.txt files

README.md
I don't use platformio to test your instructions @kisvegabor 😅 
Closes #168
=> Update README with instructions for platformio

components/lv_examples/Kconfig, components/lv_examples/lv_ex_conf.h, main/main.c
New try with the updated `lv_examples`, decided to leave the following options out of the menuconfig:
```
#define LV_EX_KEYBOARD     0       /*Add PC keyboard support to some examples (`lv_drivers` repository is required)*/
#define LV_EX_MOUSEWHEEL   0       /*Add 'encoder' (mouse wheel) support to some examples (`lv_drivers` repository is required)*/
/*Printer demo, optimized for 800x480*/
#define LV_USE_DEMO_PRINTER     0
```
because they are not intended to be used on ESP32, what do you think @kisvegabor.
=> lv_examples: Add Kconfig to lv_examples and choose an example to run on the menuconfig interface

main/main.c
I'm working on cleaning up a bit the main.c file, next step (not in this PR) would be to switch `LV_HOR_RES_MAX` and `LV_VER_RES_MAX` using the rotated field on the driver instead of manually on the `Kconfig` or `lv_conf` files.
=> main: Work buffer cleanup when working with monochrome displays

components/lvgl_esp32_drivers/lvgl_helpers.c, components/lvgl_esp32_drivers/lvgl_tft/disp_spi.c
This update switches SPI displays to used a pool of spi_transaction_ext_t structures for DMA transactions and resolves #203. It reduces DMA transaction latency and thus increases overall transfer throughput. This is completely transparent to all existing drivers but for those that burst multiple DMA requests (such as the FT81x, il3820, jd79653a, uc8151d, etc...) it can have a really big impact on overall display responsiveness and animation speeds. It also better supports LVGL's dual buffer mechanism by making the SPI thread wait less.
This is enabled for all existing display drivers but the old behavior can be re-enabled by setting SPI_TRANSACTION_POOL_SIZE to 1. That effectively reverts to the old behavior of sending 1 transactions and a time and waiting for it to complete before …
=> Switch to using a pool of DMA transactions for reduced latency

CMakeLists.txt, README.md
In this PR I have removed 'Temporal workaround' section in README and fixed related problem described in #85 issue (see [my comment](https://github.com/lvgl/lv_port_esp32/issues/85#issuecomment-701982298)).
Looks like everything is working as expected after these changes (I can reconfigure and build this and my projects without any compilation errors).
@C47D @Mair Could you please review this PR?
=> Remove 'Temporal workaround' section in README and fix related problem

components/lvgl/Kconfig, components/lvgl/lv_conf.h, components/lvgl_esp32_drivers/lvgl_tft/Kconfig
This is to cleanup the `lv_conf` file from configuration depending on the chosen driver, the configuration is solved at `Kconfig` level.
All this work is towards using lvgl as a esp-idf component.
=> Remove drivers symbols on lv_conf.

README.md
Let the users know they now will have to configure LVGL color depth and swap 16 colors in the lvgl menuconfig, it's no longer done automagically.
This is the follor up of #210
=> README: Add table with supported display controllers and configurations.

components/lvgl_esp32_drivers/lvgl_i2c_conf.h, components/lvgl_esp32_drivers/lvgl_tft/EVE_config.h, components/lvgl_esp32_drivers/lvgl_tft/FT81x.h, components/lvgl_esp32_drivers/lvgl_tft/GC9A01.h, components/lvgl_esp32_drivers/lvgl_tft/disp_driver.h, components/lvgl_esp32_drivers/lvgl_tft/disp_spi.c, components/lvgl_esp32_drivers/lvgl_tft/hx8357.h, components/lvgl_esp32_drivers/lvgl_tft/il3820.h, components/lvgl_esp32_drivers/lvgl_tft/ili9341.h, components/lvgl_esp32_drivers/lvgl_tft/ili9481.h, components/lvgl_esp32_drivers/lvgl_tft/ili9486.h, components/lvgl_esp32_drivers/lvgl_tft/ili9488.h, components/lvgl_esp32_drivers/lvgl_tft/jd79653a.h, components/lvgl_esp32_drivers/lvgl_tft/ra8875.h, components/lvgl_esp32_drivers/lvgl_tft/sh1107.h, components/lvgl_esp32_drivers/lvgl_tft/ssd1306.h, components/lvgl_esp32_drivers/lvgl_tft/st7735s.h, components/lvgl_esp32_drivers/lvgl_tft/st7789.h, components/lvgl_esp32_drivers/lvgl_touch/FT81x.h, components/lvgl_esp32_drivers/lvgl_touch/adcraw.h, components/lvgl_esp32_drivers/lvgl_touch/ra8875_touch.h, components/lvgl_esp32_drivers/lvgl_touch/stmpe610.h, components/lvgl_esp32_drivers/lvgl_touch/touch_driver.h, components/lvgl_esp32_drivers/lvgl_touch/xpt2046.h
When LV_LVGL_H_INCLUDE_SIMPLE is not defined (the default) then
`"lvgl/lvgl.h"` is included, else `"lvgl.h"` is included.
This is for other build systems (like PlatformiIO) which setup
build paths differently than esp-idf. More info in issue #220.
This approach is identical to that used by https://github.com/lvgl/lv_drivers.
=> Including "lvgl.h" if LV_LVGL_H_INCLUDE_SIMPLE is defined.

components/lvgl_esp32_drivers/lvgl_helpers.c
PlatformIO compiles using a different include path strategy than
esp-idf. If PLATFORMIO is defined then `"lv_core/lv_refr.h"` will
be included, otherwise `"lvgl/src/lv_core/lv_refr.h"`. More info
in issue #220.
=> Including lv_core/lv_refr.h differently form platformio.

components/lvgl_esp32_drivers/lvgl_touch/ft6x36.c
This was missed and should have been part of 31c6ed0154600dd9ebe78f3538ed479be8b12aea.
=> Including lvgl.h differently based on LV_LVGL_H_INCLUDE_SIMPLE.

components/lvgl_esp32_drivers/lvgl_helpers.c
This reverts commit 31c6ed0154600dd9ebe78f3538ed479be8b12aea.
The reverted change enabled a PlatformIO project to build lv_port_esp32
when adding it as a library dependency using the platformio.ini
lib_deps[¹] value. Unfortunately it broke the PlatformIO build when
building this project (i.e. main/main.c). Reverting and hopefully
coming up with a better solution.
[¹]: https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-deps
=> Revert "Including lv_core/lv_refr.h differently form platformio."

README.md
Problem:
CMake cannot find the main component when it is configuring. This is cause by the set command overwriting the component list. Appending to the component list is a safer procedure.
Test Setup:
1. Initialize Platformio espidf blink example
2. Follow [these](https://github.com/lvgl/lv_port_esp32#install-this-project-as-a-library-submodule-in-your-own-project) steps from the readme file
3. Observe build errors
=> Set overwrites main component

main/CMakeLists.txt
This fixes a compilation issue with (at least) `ESP-IDF 4.2`, as with original code libraries were duplicated in `LINK_LIBRARIES` targetand the "second copy" of `lv_examples.a` was placed after `lvgl.a`, causing build failure with lots of `undefined references`)
=> Fix build ESP-IDF 4.2

README.md
Hi,
This PR adds some formatting fixes to the README.
=> Minor updates in the README

README.md
Partially address #256, until we achieve support for ESP32-S2 targets.
=> README: Document ESP32-S2 as not (yet) officially supported

components/lv_examples/Kconfig
Unable to deselect LV_DEMO_WIDGETS_SLIDESHOW
=> Fix for lv_example slideshow setting

CMakeLists.txt, Makefile, components/lv_examples/CMakeLists.txt, components/lv_examples/component.mk, main/CMakeLists.txt, main/component.mk, main/main.c
Latest `lvgl_esp32_drivers` changes its component structure. This project has to be updated for it.
TODOs:
=> Remove Extra component dirs definition

.github/workflows/build.yml
This is a preview how to run ESP-IDF build from Github Actions.
It's a 'preview' because there are few limitations:
- ~~We still need `lv_port_esp32` repo to run build action, because `lvgl_esp32_drivers` doesn't contain examples that can be built into a full app~~ There are examples and build action now in `lvgl_esp32_drivers`
- ~~Currently only default example configuration is built. Thus only ILI9341 driver is compiled. Ultimately we need to compile all drivers in one build action~~. `master` of `lvgl_esp32_drivers` builds all drivers
Above-mentioned issues will be addressed in https://github.com/lvgl/lvgl_esp32_drivers/issues/72
=> Add esp-build action
