- drv/ili9341.c
- drv/ili9341.h
- main/main.c
Spent nearly an entire afternoon attempting to get this to work in parallel mode only to find out my board has an __ili9481__ driver and this project is for the __ili9341__ despite having __ili9431__ in the title.  
The title/repo should also be corrected.
> Rename ili9431 and ili9441 to ili9341

- README.md
Updates the repo link on the readme, this is because the rename of the repo.
> [README] Update repo link

- main/main.c
> [main] Include tp_spi and xpt2046 only when input touch is enabled

- .github/ISSUE_TEMPLATE/issue-template.md
Hi,
@kisvegabor, could you help us to get this file as an issue template for this repo? I tried to follow the issue template of the main lvgl repo.
Let me know if you have any suggestions.
Regards
> [ISSUE_TEMPLATE] First implementation of the issue template

- main/main.c
> Fix touch ignored

- components/lvgl_esp32_drivers/lvgl_tft/st7789.c
- components/lvgl_esp32_drivers/lvgl_tft/st7789.h
> Initial support for ST7789 TFT Controller

- components/lvgl_esp32_drivers/lvgl_tft/disp_driver.c
- components/lvgl_esp32_drivers/lvgl_tft/disp_driver.h
- components/lvgl_esp32_drivers/lvgl_tft/disp_spi.c
- components/lvgl_esp32_drivers/lvgl_touch/ft6x36.c
- components/lvgl_esp32_drivers/lvgl_touch/ft6x36.h
- components/lvgl_esp32_drivers/lvgl_touch/touch_driver.c
- components/lvgl_esp32_drivers/lvgl_touch/touch_driver.h
- main/main.c
Updates the main.c file to use the new touch driver abstaction layer.
> Update touch driver and main.c

- components/lvgl_esp32_drivers/lvgl_touch/Kconfig
- components/lvgl_esp32_drivers/lvgl_touch/tp_spi.c
> Fix SPI transfer mode when reading and writing to touch controller 

- CMakeLists.txt
- README.md
Temprary (hopefully) workaround so this project can be used also as component.
> README: Document workaround when using this project as component

- components/lvgl/lv_conf.h
- components/lvgl_esp32_drivers/lvgl_driver.c
- components/lvgl_esp32_drivers/lvgl_tft/Kconfig
- components/lvgl_esp32_drivers/lvgl_tft/disp_driver.c
- components/lvgl_esp32_drivers/lvgl_tft/disp_driver.h
- components/lvgl_esp32_drivers/lvgl_tft/disp_spi.c
- components/lvgl_esp32_drivers/lvgl_tft/ili9486.c
- components/lvgl_esp32_drivers/lvgl_tft/ili9486.h
- components/lvgl_esp32_drivers/lvgl_touch/Kconfig
- components/lvgl_esp32_drivers/lvgl_touch/xpt2046.c
- components/lvgl_esp32_drivers/lvgl_touch/xpt2046.h
The MPI3501 display is based on the ILI9486 tft controller and XPT2046 touch controller.
> Initial implementation to support MPI3501 by @ndunello

- components/lvgl/lv_conf.h
- components/lvgl_esp32_drivers/lvgl_tft/Kconfig
- components/lvgl_esp32_drivers/lvgl_tft/ili9341.c
Fix rotation of ILI9341 based displays when not using a predefined kit.
> Ili9341 rotation

- components/lvgl_esp32_drivers/lvgl_tft/ili9486.c
> Ili9486 rotation

- main/main.c
Sorry if I misunderstood something but docs say lv_tick should be called with interval period in ms.
> According to docs lv_tick_inc should be run with interval duration in ms

- CMakeLists.txt
This updates CMakeLists.txt for be compatible for both ESP-IDF and PlatformIO build systems
> Updated CMakeLists.txt for PlatformIO

- PRECONFIGURED_KITS.md
- components/lvgl/lv_conf.h
- components/lvgl_esp32_drivers/lvgl_tft/Kconfig
- components/lvgl_esp32_drivers/lvgl_tft/ssd1306.c
Based on #150 and #151 from @an-erd .
> St7735s update

- components/lvgl/Kconfig
- components/lvgl/lv_conf.h
Add the input device settings in the menuconfig.
> LVGL Kconfig: Add Input device settings into the menuconfig

- components/lvgl/Kconfig
- components/lvgl/lv_conf.h
> lvgl kconfig: Add some of the missing configuration options into the menuconfig interface

- components/lvgl_esp32_drivers/lvgl_tft/Kconfig
- components/lvgl_esp32_drivers/lvgl_tft/il3820.c
- components/lvgl_esp32_drivers/lvgl_tft/il3820.h
- main/main.c
Preparing the IL3820 for portrait and landscape support, it currently crashes when configured as portrait.
> IL3820 driver cleanup

- components/lvgl_esp32_drivers/lvgl_tft/FT81x.c
> Fix for FT81x screen size settings

- components/lvgl_esp32_drivers/lvgl_helpers.c
- components/lvgl_esp32_drivers/lvgl_spi_conf.h
- components/lvgl_esp32_drivers/lvgl_tft/Kconfig
- components/lvgl_esp32_drivers/lvgl_touch/Kconfig
> Esp32s2 aware

- README.md
> Update README.md missing bracket

- main/main.c
> Fix demo keypad and encoder include
